### ISSUE TITLE
App close information gathering

### ISSUE THREAD

**Issue by narfman0** [guardian/toolargetool#2]
Hello! This looks awesome/helpful/interesting, thanks!

Upon app close, when saving state, it is bringing up the "App has crashed" error dialog for me. In [this thread ](https://code.google.com/p/android/issues/detail?id=212316) a target app developer [took a video and posted](https://drive.google.com/file/d/0B-eHYVYyBpyjUjExemRVYTk5bXM/view?usp=sharing) a similar issue. Does this tool help debug those things too?

Note: I'd expect that a lot of Bundle serializing boosts parcel size, but doesn't crash til app close. Does this tool work until app close..?

**Comment by narfman0** [comment]
Followup: I was saving ~250KB in a particular fragments bundle, the result of an api call. I really don't want the user to make another call upon app load, so I'm saving to disk and the error goes away. Thanks though cool tool!

**Comment by maxspencer** [comment]
@narfman0 glad you were able to find and solve the problem. Thanks!
