### ISSUE TITLE
causes  static method cannot be referenced from a non static context

### ISSUE THREAD

**Issue by pawaom** [guardian/toolargetool#25]
causes non static method 'startLogging(android.app.Application) cannot be referenced from a static context

I have a class which extends Application when I tried to use TooLargeTool.startLogging(this); in oncreate method it causes non static method 'startLogging(android.app.Application) cannot be referenced from a static context

even when i tried to use it in Mainactivity which extends activity in oncreate method it caused same error 

pelase can you proivde a proper soultion and an example app as early as possible

ps:  I am using Androidx, could this be causing some issues

**Comment by shalus** [comment]
Faced the same. You can use INSTANCE keyword. TooLargeTool.INSTANCE.startLogging(this);

**Comment by joshuapinter** [comment]
How is this not in the `README.md`?

**Comment by maxspencer** [comment]
Apologies for causing this problem, it was an unintended consequence of the transition to Kotlin. As @shalus says, using `TooLargeTool.INSTANCE.startLogging(this)` works, but this will be properly resolved in the next version by #27

**Comment by joshuapinter** [comment]
Nice. Thanks for acknowledging and fixing, @maxspencer! 👏

**Comment by joshuapinter** [comment]
So to be clear, we can call it with `TooLargeTool.startLogging(this)` with the change in #27?

Also, what version was this released in? 

(P.s. I highly recommend creating proper Releases in Github or at the very least a `CHANGELOG.md` file so everybody knows what the versions are and what the changes are in them.)

**Comment by maxspencer** [comment]
> So to be clear, we can call it with `TooLargeTool.startLogging(this)` with the change in #27?

That's right,

> Also, what version was this released in?

0.2.1

> (P.s. I highly recommend creating proper Releases in Github or at the very least a `CHANGELOG.md` file so everybody knows what the versions are and what the changes are in them.)

Sound advice, I'll try both those suggestions for the next release. Thanks again 👍
