### ISSUE TITLE
will this lib be accessible after jcenter is sunset?

### ISSUE THREAD

**Issue by meyn** [guardian/toolargetool#37]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by maxspencer** [comment]
Hi @meyn, thanks for raising this - at The Guardian we're collectively working out the best way to migrate all our libs off jcenter and I will apply whatever solution we come up with to this lib in due course :+1:

**Comment by maxspencer** [comment]
TooLargeTool is now available from Maven Central, I've updated the [README instructions](https://github.com/guardian/toolargetool#usage) to reflect that, but basically you should just be able to drop the old Guardian Bintray repository declaration and Gradle will pick it up from `mavenCentral()` instead (assuming you have that repo declared already).
