### ISSUE TITLE
Failed to resolve: com.gu.android:toolargetool:0.1.3

### ISSUE THREAD

**Issue by ulohani90** [guardian/toolargetool#8]
Not able to add the library to my project 
Have added dependency both to build.gradle( both project and module level)

**Comment by saxmaster79** [comment]
I have the same problem

**Comment by svvashishtha** [comment]
@ulohani90 
Try adding the project level dependency to 
`allprojects-> repositories`

 block instead of 

`buildscript->repositories`


Like this: 
`allprojects{
    repositories{
          jcenter()
          maven { url 'https://dl.bintray.com/guardian/android' }
    }
}`

**Comment by maxspencer** [comment]
Like @svvashishtha says, ensure you're adding the new repository inside the `allprojects` closure not the `buildscript` one, e.g.:

```
allprojects {
    repositories {
        jcenter()
        maven { url 'https://dl.bintray.com/guardian/android' }
    }
}
```
